In [15]:
import numpy as np

In [20]:
A = np.array([[6.23, 1.97, 3.08, 1.43, 1, 0, 0, 0],
              [2.94, 6.34, 5.84, 1.85, 0, 1, 0, 0],
              [2.84, 5.42, 6.03, 1.71, 0, 0, 1, 0],
              [1.67, 2.75, 1.26, 5.25, 0, 0, 0, 1],])
L = np.zeros((4,4))
U = np.eye(4)
L,U

(array([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]),
 array([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]]))

In [21]:
for i in range(4):
    L[i, 0] = A[i, 0]
    
print(np.round(L,4),'\n', np.round(U,4))

for i in range(1,4):
    U[0, i] = A[0, i] / L[0, 0]
    L[i, 1] = A[i, 1] - L[i, 0] * U[0, 1]

print(np.round(L,4),'\n', np.round(U,4))
    
for i in range(2,4):
    U[1, i] = (A[1, i] - L[1, 0] * U[0, i]) / L[1, 1]
    L[i, 2] = A[i, 2] - L[i, 0] * U[0, 2] - L[i, 1] * U[1, 2]
    
print(np.round(L,4),'\n', np.round(U,4))

for i in range(3,4):
    U[2, i] = (A[2, i] - L[2, 0] * U[0, i] - L[2, 1] * U[1, i]) / L[2, 2]
    L[i, 3] = A[i, 3] - L[i, 0] * U[0, 3] - L[i, 1] * U[1, 3] - L[i, 2] * U[2, 3]
    
print(np.round(L,4),'\n', np.round(U,4))

[[6.23 0.   0.   0.  ]
 [2.94 0.   0.   0.  ]
 [2.84 0.   0.   0.  ]
 [1.67 0.   0.   0.  ]] 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[6.23   0.     0.     0.    ]
 [2.94   5.4103 0.     0.    ]
 [2.84   4.522  0.     0.    ]
 [1.67   2.2219 0.     0.    ]] 
 [[1.     0.3162 0.4944 0.2295]
 [0.     1.     0.     0.    ]
 [0.     0.     1.     0.    ]
 [0.     0.     0.     1.    ]]
[[ 6.23    0.      0.      0.    ]
 [ 2.94    5.4103  0.      0.    ]
 [ 2.84    4.522   0.9597  0.    ]
 [ 1.67    2.2219 -1.3671  0.    ]] 
 [[1.     0.3162 0.4944 0.2295]
 [0.     1.     0.8108 0.2172]
 [0.     0.     1.     0.    ]
 [0.     0.     0.     1.    ]]
[[ 6.23    0.      0.      0.    ]
 [ 2.94    5.4103  0.      0.    ]
 [ 2.84    4.522   0.9597  0.    ]
 [ 1.67    2.2219 -1.3671  4.4922]] 
 [[1.     0.3162 0.4944 0.2295]
 [0.     1.     0.8108 0.2172]
 [0.     0.     1.     0.0791]
 [0.     0.     0.     1.    ]]


In [18]:
det = 1
for i in range(4):
    det *= L[i,i]
det

145.3146095400001

In [5]:
A = np.array([[6.23, 1.97, 3.08, 1.43],
              [2.94, 6.34, 5.84, 1.85],
              [2.84, 5.42, 6.03, 1.71],
              [1.67, 2.75, 1.26, 5.25]])
print(np.linalg.det(A))

145.31460954000013
