In [17]:
import numpy as np

In [18]:
a = np.array([0, 3.6, 2.2, 3])
b = np.array([6.5, 5.9, 4.3, 4.7]) * (-1)
c = np.array([-1.4, -1.5, -0.6, 0])
d = np.array([4.6, 3.7, 3.1, 7.7])

In [19]:
np.abs(b) >= np.abs(a) + np.abs(c)

array([ True,  True,  True,  True])

In [23]:
l = np.zeros(len(b)-1)
g = np.zeros(len(b)-1)
l[0] = c[0] / b[0]
g[0] = (-1) * d[0] / b[0]

for i in range(1,len(b) - 1):
    l[i] = c[i] / (b[i] - a[i] * l[i-1])

for i in range(1,len(b) - 1):
    g[i] = (a[i] * g[i-1] - d[i]) / (b[i] - a[i] * l[i-1])
l, g

(array([0.21538462, 0.22470615, 0.12514722]),
 array([0.70769231, 0.17262042, 0.56738308]))

In [24]:
l <= 1

array([ True,  True,  True])

In [25]:
x = np.zeros(len(b))
x[-1] = (d[-1] - a[-1] * g[-2]) / (a[-1] * l[-2] - b[-1])

for i in np.flip(np.arange(0, len(b)-1 )):
    x[i] = l[i] * x[i+1] + g[i]
x

array([0.78042707, 0.33769713, 0.73463371, 1.33643104])